### ISSUE TITLE
Video list not generated for 99kubo.tv 

### ISSUE THREAD

**Issue by mk8kim** [ypchen/plugin.video.hdp_ims#1]
As of today, I noticed that the video list is not being generated properly (shows empty) for any of the categories.

Perhaps it has to do with 99kubo.tv domain being changed to http://www.iwatchme2u.com/ ?

**Comment by ypchen** [comment]
I tested it yesterday and also today. Everything seems normal at my end. The domain name 99kubo.tv works fine for me. (I fixed a 'https' -> 'http' issue with quickfix for playing, though)

Maybe it's some temporary outage for you?

**Comment by mk8kim** [comment]
I appreciate you getting back to me. I tried a complete reset of everything on two different operating systems; First on PC (Windows 10, Kodi 18.7) and then on Nvidia Shield (Android TV, Kodi 18.6), but still getting the same result.

Would you be able to take a look at this video recording when you get a chance?
https://youtu.be/r1eG6bn6zSY

Prior to facing this issue, if I were to go into a video category (ex. Drama), I would have different languages to choose from (Chinese, Taiwanese, English, Korean, etc) and then videos corresponding to that category and language.

Any idea what may be causing this issue?

Thank you in advance.

**Comment by ypchen** [comment]
Interesting...

I did some tests. Although I am not 100% sure, I do think the issue is caused by the geographical region of IPs.

I used VPNs to switch my IP to Japan and South Korea. "99kubo.tv" then became not working even with my browser. 

I also investigated into the feasibility of replacing "99kubo.tv" with "iwatchme2u.com," and found that simply replacing the domain name does not work, because 99kubo.tv and iwatchme2u.com have different URL conventions. Moreover, iwatchme2u.com seems obsolete because there is no "2020" menu item.

If possible, perhaps you can try to use a VPN server in Taiwan to see whether everything works.
